/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package qltour.view;

import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;

import java.awt.Checkbox;
import java.awt.Color;
import java.util.ArrayList;

import javax.swing.border.LineBorder;
import javax.swing.event.AncestorEvent;
import javax.swing.event.AncestorListener;
import javax.swing.JScrollPane;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import qltour.check_loi.check_Loi;
import qltour.managedata.IO;
import qltour.model.HopDong;
import qltour.model.KhachHang;
import qltour.model.Tour;

import javax.swing.SwingConstants;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.GridLayout;
import java.awt.Label;
import java.awt.SystemColor;
import java.awt.event.ActionListener;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.time.LocalDate;

import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.border.CompoundBorder;
import javax.swing.JComboBox;
import javax.swing.JDialog;

import java.awt.Component;
import java.awt.Dialog;

import javax.swing.JTextField;
import javax.swing.JRadioButton;
import javax.swing.JScrollBar;
import javax.swing.JButton;
import javax.swing.ButtonGroup;
import java.awt.event.ActionEvent;
import javax.swing.AbstractAction;
import javax.swing.Action;
import java.awt.Font;
import javax.swing.JPanel;
import java.awt.Window;

public class bai2 extends javax.swing.JPanel {
	private JTable table;
	static IO o = new IO();
	ArrayList<HopDong> listHD = new ArrayList<HopDong>();
	private ArrayList<KhachHang> listKH;
	private ArrayList<Tour> listTour;
	private JButton btnAdd;
	private JButton btnXoa;
	private JButton btnSua;
	private JDialog edit_jDialog;
	private JLabel lb1;
	private JTextField tf1, tf2;
	private JLabel lb_mahopdong, lb_NgayLap, lb_maTour, lb_KH, lb_Trangthai;
	private JTextField tf_MHD, tf_NgayLap;
	private JComboBox comboBox_MKH;
	private JComboBox comboBox_MaTour;
	private JRadioButton RB1;
	private JRadioButton RB2;
	private JButton btnedit,btnadd;

	private final ButtonGroup buttonGroup = new ButtonGroup();
	private JLabel lblNewLabel;
	/**
	 * @wbp.nonvisual location=474,149
	 */
	/**
	 * @wbp.nonvisual location=371,449
	 */
	private JDialog dialog = new JDialog();

	public bai2() {

		initComponents();
		setTable();
	}

	private void setTable() {
		DefaultTableModel defaultTableModel = new DefaultTableModel();
		table.setBackground(new Color(204, 255, 255));
		table.setModel(defaultTableModel);
		ListSelectionModel listSelectionModel = table.getSelectionModel();
		listSelectionModel.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
		defaultTableModel.addColumn("STT");
		defaultTableModel.addColumn("Mã hợp đồng");
		defaultTableModel.addColumn("Mã tour");
		defaultTableModel.addColumn("Mã khách hàng");
		defaultTableModel.addColumn("Ngày lập");
		defaultTableModel.addColumn("Trạng thái thanh toán");
		listHD = o.loadData(listHD, "dsHD.dat");
		int i = 0;
		for (HopDong Hopdong : listHD) {
			i++;
			defaultTableModel.addRow(new Object[] { i, Hopdong.getID_HopDong(), Hopdong.getMaTour(), Hopdong.getMaKh(),
					Hopdong.getNgayLap(), Hopdong.getTrangThai() });
		}
		JScrollPane jScrollPane = new JScrollPane();
		table.add(jScrollPane);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {
		edit_jDialog = new JDialog();
		table = new JTable();
		listKH = new ArrayList<KhachHang>();
		listTour = new ArrayList<Tour>();

		setBackground(new Color(176, 224, 230));

		JScrollPane scrollPane = new JScrollPane();
		scrollPane.setBackground(new Color(153, 204, 153));
		comboBox_MKH = new JComboBox();
		comboBox_MKH.setFont(new Font("Tahoma", Font.PLAIN, 14));
		listKH = o.loadData(listKH, "dsKh.dat");
		for (KhachHang kh : listKH) {
			comboBox_MKH.addItem(kh.getID_client());
		}
		comboBox_MaTour = new JComboBox();
		comboBox_MaTour.setFont(new Font("Tahoma", Font.PLAIN, 14));
		listTour = o.loadData(listTour, "dsTour1.dat");
		for (Tour t : listTour) {
			comboBox_MaTour.addItem(t.getID_Tour());
		}

		table.addMouseListener(new MouseListener() {

			@Override
			public void mouseReleased(MouseEvent e) {
				// TODO Auto-generated method stub

			}

			@Override
			public void mousePressed(MouseEvent e) {
				// TODO Auto-generated method stub

			}

			@Override
			public void mouseExited(MouseEvent e) {
				// TODO Auto-generated method stub

			}

			@Override
			public void mouseEntered(MouseEvent e) {
				// TODO Auto-generated method stub

			}

			@Override
			public void mouseClicked(MouseEvent e) {
				// TODO Auto-generated method stub
				tf_MHD.setText(listHD.get(table.getSelectedRow()).getID_HopDong());
				tf_NgayLap.setText(listHD.get(table.getSelectedRow()).getNgayLap());
				Object tmp1 = listHD.get(table.getSelectedRow()).getMaTour();
				comboBox_MaTour.setSelectedItem(tmp1);
				;
				Object tmp2 = listHD.get(table.getSelectedRow()).getMaKh();
				comboBox_MKH.setSelectedItem(tmp2);
				if (listHD.get(table.getSelectedRow()).getTrangThai().compareTo("Chưa thanh toán") == 0)
					RB2.setSelected(true);
				else
					RB1.setSelected(true);
			}
		});
		JButton btnAdd = new JButton("Thêm");
		btnAdd.setFont(new Font("Tahoma", Font.PLAIN, 14));
		btnAdd.addActionListener(new ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				add_jButtonActionPerformed(evt);
			}
		});
		btnXoa = new JButton("Xoá");
		btnXoa.setFont(new Font("Tahoma", Font.PLAIN, 14));
		btnXoa.addActionListener(new ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				del_jButtonActionPerformed(evt);
			}
		});

		btnSua = new JButton("Sửa");
		btnSua.setFont(new Font("Tahoma", Font.PLAIN, 14));

		btnSua.addActionListener(new ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				edit_jButtonActionPerformed(evt);
			}
		});
		lb_mahopdong = new JLabel("  Mã hợp đồng");
    	lb_KH= new JLabel("  Mã khách hàng");
    	lb_maTour =new JLabel("  Mã Tour");
    	lb_NgayLap= new JLabel("  Ngày lập");
    	lb_Trangthai = new JLabel("  Trạng thái");
    	 tf_MHD = new JTextField();
    	 tf_NgayLap = new JTextField();
         RB1 = new JRadioButton("Đã thanh toán");
         RB2 = new JRadioButton("Chưa thanh toán");

		JPanel panel = new JPanel();
		panel.setBackground(SystemColor.inactiveCaption);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
		layout.setHorizontalGroup(
			layout.createParallelGroup(Alignment.TRAILING)
				.addComponent(panel, GroupLayout.DEFAULT_SIZE, 1026, Short.MAX_VALUE)
				.addComponent(scrollPane, GroupLayout.DEFAULT_SIZE, 1026, Short.MAX_VALUE)
				.addGroup(layout.createSequentialGroup()
					.addContainerGap(173, Short.MAX_VALUE)
					.addComponent(btnAdd, GroupLayout.PREFERRED_SIZE, 157, GroupLayout.PREFERRED_SIZE)
					.addGap(136)
					.addComponent(btnSua, GroupLayout.PREFERRED_SIZE, 157, GroupLayout.PREFERRED_SIZE)
					.addGap(116)
					.addComponent(btnXoa, GroupLayout.PREFERRED_SIZE, 157, GroupLayout.PREFERRED_SIZE)
					.addGap(130))
		);
		layout.setVerticalGroup(
			layout.createParallelGroup(Alignment.TRAILING)
				.addGroup(layout.createSequentialGroup()
					.addComponent(panel, GroupLayout.PREFERRED_SIZE, 92, GroupLayout.PREFERRED_SIZE)
					.addGap(37)
					.addComponent(scrollPane, GroupLayout.PREFERRED_SIZE, 263, GroupLayout.PREFERRED_SIZE)
					.addPreferredGap(ComponentPlacement.RELATED, 113, Short.MAX_VALUE)
					.addGroup(layout.createParallelGroup(Alignment.BASELINE)
						.addComponent(btnXoa, GroupLayout.PREFERRED_SIZE, 55, GroupLayout.PREFERRED_SIZE)
						.addComponent(btnSua, GroupLayout.PREFERRED_SIZE, 55, GroupLayout.PREFERRED_SIZE)
						.addComponent(btnAdd, GroupLayout.PREFERRED_SIZE, 55, GroupLayout.PREFERRED_SIZE))
					.addGap(188))
		);
		
		lblNewLabel = new JLabel("Quản Lý Hợp Đồng");
		panel.add(lblNewLabel);
		lblNewLabel.setFont(new Font("Tahoma", Font.PLAIN, 34));
		scrollPane.setViewportView(table);
		this.setLayout(layout);
	}// </editor-fold>//GEN-END:initComponents

	private void add_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_jButtonActionPerformed
        // TODO add your handling code here:
		
		
		dialog = new JDialog();
    	dialog.setAlwaysOnTop(true);
    	dialog.setTitle("Thêm Hợp Đồng");
    	dialog.setFont(new Font("Dialog", Font.PLAIN, 15));
    	JPanel jPanel_1= new JPanel();
    	jPanel_1.setLayout(new GridLayout(6,2,30,30));
    	dialog.getContentPane().setLayout(new GridLayout(2,1,30,0));
    	dialog.getContentPane().setBackground(new Color(176,224,230));
//    	lb_mahopdong = new JLabel("  Mã hợp đồng");
//    	lb_KH= new JLabel("  Mã khách hàng");
//    	lb_maTour =new JLabel("  Mã Tour");
//    	lb_NgayLap= new JLabel("  Ngày lập");
//    	lb_Trangthai = new JLabel("  Trạng thái");
//    	 tf_MHD = new JTextField();
//    	 tf_NgayLap = new JTextField();
//         RB1 = new JRadioButton("Đã thanh toán");
//         RB2 = new JRadioButton("Chưa thanh toán");
    	jPanel_1.add(lb_mahopdong);
    	jPanel_1.add(tf_MHD);
    	jPanel_1.add(lb_NgayLap);
    	jPanel_1.add(tf_NgayLap);
    	jPanel_1.add(lb_maTour);
    	jPanel_1.add(comboBox_MaTour);
    	jPanel_1.add(lb_KH);
    	jPanel_1.add(comboBox_MKH);
    	jPanel_1.add(lb_Trangthai);
    	JPanel jPanel = new JPanel(new FlowLayout());
    	jPanel.add(RB1);
    	jPanel.add(RB2);
    	JButton btnadd= new JButton("Thêm Hợp Đồng");
    	dialog.getContentPane().add(jPanel_1);
    	JPanel jPanel2 = new JPanel(new GridLayout(1,1,100,50));
    	jPanel2.add(btnadd);
    	jPanel_1.setBackground(new Color(176,224,230));
    	jPanel_1.add(jPanel);
    	jPanel_1.add(btnadd);
    	RB2.setSelected(true);
    	dialog.setSize(550,650);
    	RB1.addActionListener( new java.awt.event.ActionListener() {
			@Override
			public void actionPerformed(ActionEvent e) {
				RB2.setSelected(false);
				
			}
		});
    	RB2.addActionListener( new java.awt.event.ActionListener() {
			@Override
			public void actionPerformed(ActionEvent e) {
				RB1.setSelected(false);
				
			}
		});
    	btnadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {

                listHD = o.loadData(listHD, "dsHD.dat");
                String MaHD= tf_MHD.getText();
                String  MaKH=(String) comboBox_MKH.getSelectedItem()  ;
                tf_NgayLap.setText(String.valueOf(LocalDate.now()));
                String NgayLap= tf_NgayLap.getText();
                String trangThai="";
                if(RB1.isSelected()) trangThai="Đã thanh toán";
                else if(RB2.isSelected()) trangThai="Chưa thanh toán";
                String MaTour= (String) comboBox_MaTour.getSelectedItem();
                
                if(MaHD.isEmpty()) JOptionPane.showMessageDialog(dialog, "Không để trống thông tin","Lỗi",JOptionPane.ERROR_MESSAGE);
                else if(NgayLap.isEmpty()) JOptionPane.showMessageDialog(dialog, "Không để trống thông tin","Lỗi",JOptionPane.ERROR_MESSAGE);
                else {
                	boolean find = false;
                	for(HopDong hd : listHD) {
                		if(hd.getID_HopDong().compareTo(MaHD)==0) {
                			JOptionPane.showMessageDialog(dialog, "Trùng Mã Hợp Đồng","Lỗi",JOptionPane.ERROR_MESSAGE);
                			find = true ;
                    		break;
                		}
                		
                	}
                	if(!find) {
                		HopDong hd= new HopDong(MaHD,MaKH , NgayLap, trangThai,MaTour);
                        listHD.add(hd);
                        JOptionPane.showMessageDialog(dialog, "Thêm thành công","Thông báo",JOptionPane.INFORMATION_MESSAGE);
                        o.saveData(listHD, "dsHD.dat");
                        setTable();
                	}
                }
        }});
    	
//    	lb_mahopdong = new JLabel("  Mã hợp đồng");
//    	lb_KH= new JLabel("  Mã khách hàng");
//    	lb_maTour =new JLabel("  Mã Tour");
//    	lb_NgayLap= new JLabel("  Ngày lập");
//    	lb_Trangthai = new JLabel("  Trạng thái");
//    	 tf_MHD = new JTextField();
//    	 tf_NgayLap = new JTextField();
    	dialog.setBackground(Color.blue);
    	dialog.setVisible(true);
    	

    	
        
    }

	private void del_jButtonActionPerformed(java.awt.event.ActionEvent evt) {
		
		if (table.getSelectedRow() < 0)
			JOptionPane.showMessageDialog(this, "Vui lòng chọn hợp đồng cần xoá", "Lỗi",
					JOptionPane.ERROR_MESSAGE);
		else {
			listHD = o.loadData(listHD, "dsHD.dat");
			int index = table.getSelectedRow();
			System.out.println(index);
			listHD.remove(index);
			o.saveData(listHD, "dsHD.dat");
			setTable();
		}
	}

	private void edit_jButtonActionPerformed(java.awt.event.ActionEvent evt) {
//    	update_view_kh_jButtonActionPerformed(evt);
		if (table.getSelectedRow() < 0)
			JOptionPane.showMessageDialog(null, "Vui lòng chọn hợp đồng cần sửa", "Lỗi",
					JOptionPane.ERROR_MESSAGE);
		else {
			dialog = new JDialog();
	    	dialog.setAlwaysOnTop(true);
	    	dialog.setTitle("Sửa Hợp Đồng");
	    	dialog.setFont(new Font("Dialog", Font.PLAIN, 15));
	    	JPanel jPanel_1= new JPanel();
	    	jPanel_1.setLayout(new GridLayout(6,2,30,30));
	    	dialog.getContentPane().setLayout(new GridLayout(2,1,30,0));
	    	dialog.getContentPane().setBackground(new Color(176,224,230));
//	    	lb_mahopdong = new JLabel("  Mã hợp đồng");
//	    	lb_KH= new JLabel("  Mã khách hàng");
//	    	lb_maTour =new JLabel("  Mã Tour");
//	    	lb_NgayLap= new JLabel("  Ngày lập");
//	    	lb_Trangthai = new JLabel("  Trạng thái");
//	    	 tf_MHD = new JTextField();
//	    	 tf_NgayLap = new JTextField();
//	         RB1 = new JRadioButton("Đã thanh toán");
//	         RB2 = new JRadioButton("Chưa thanh toán");
	    	jPanel_1.add(lb_mahopdong);
	    	jPanel_1.add(tf_MHD);
	    	jPanel_1.add(lb_NgayLap);
	    	jPanel_1.add(tf_NgayLap);
	    	jPanel_1.add(lb_maTour);
	    	jPanel_1.add(comboBox_MaTour);
	    	jPanel_1.add(lb_KH);
	    	jPanel_1.add(comboBox_MKH);
	    	jPanel_1.add(lb_Trangthai);
	    	JPanel jPanel = new JPanel(new FlowLayout());
	    	jPanel.add(RB1);
	    	jPanel.add(RB2);
	    	btnedit= new JButton("Sửa Hợp Đồng");
	    	dialog.getContentPane().add(jPanel_1);
	    	JPanel jPanel2 = new JPanel(new GridLayout(1,1,100,50));
	    	jPanel2.add(btnedit);
	    	jPanel_1.setBackground(new Color(176,224,230));
	    	jPanel_1.add(jPanel);
	    	jPanel_1.add(btnedit);
	    	RB2.setSelected(true);
	    	dialog.setSize(550,650);
	    	RB1.addActionListener( new java.awt.event.ActionListener() {
				@Override
				public void actionPerformed(ActionEvent e) {
					RB2.setSelected(false);
					
				}
			});
	    	RB2.addActionListener( new java.awt.event.ActionListener() {
				@Override
				public void actionPerformed(ActionEvent e) {
					RB1.setSelected(false);
					
				}
			});
	    	table.addMouseListener(new MouseListener() {
				
				@Override
				// TODO Auto-generated method stub
						public void mouseReleased(MouseEvent e) {
				}
				@Override
				public void mousePressed(MouseEvent e) {
					// TODO Auto-generated method stub
				}
				@Override
				public void mouseExited(MouseEvent e) {
					// TODO Auto-generated method stub
				}
				@Override
				public void mouseEntered(MouseEvent e) {
					// TODO Auto-generated method stub
				}
				@Override
				public void mouseClicked(MouseEvent e) {
					// TODO Auto-generated method stub
					tf_MHD.setText(listHD.get(table.getSelectedRow()).getID_HopDong());
			    	tf_NgayLap.setText(listHD.get(table.getSelectedRow()).getNgayLap());
			    	Object tmp1 = listHD.get(table.getSelectedRow()).getMaTour();
			    	comboBox_MaTour.setSelectedItem(tmp1);;
			    	Object tmp2 = listHD.get(table.getSelectedRow()).getMaKh();
			    	comboBox_MKH.setSelectedItem(tmp2);
			    	if(listHD.get(table.getSelectedRow()).getTrangThai().compareTo("Chưa thanh toán")==0) RB2.setSelected(true);
			    	else RB1.setSelected(true);
				}
			});
	    	btnedit.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	            	listHD = o.loadData(listHD, "dsHD.dat");
	        		String mahd;
	        			mahd = listHD.get(table.getSelectedRow()).getID_HopDong();
	        			boolean find = false;
	        			if(tf_MHD.getText().compareTo("")==0) {
	        				JOptionPane.showMessageDialog(dialog, "Không để trống ID","Lỗi",JOptionPane.ERROR_MESSAGE);
	        			}else {
	        				for (HopDong hd : listHD) {
		        				if (hd.getID_HopDong().compareTo(tf_MHD.getText()) == 0) {
		        					if (tf_MHD.getText().compareTo(mahd) == 0)
		        						find = false;
		        					else {
		        						find = true;
		        						JOptionPane.showMessageDialog(dialog, "Không đặt trùng ID", "Thông báo",
		        								JOptionPane.ERROR_MESSAGE);
		        					}
		        					break;
		        				}
		        			}
		        			if (!find) {
		        				listHD.get(table.getSelectedRow()).setID_HopDong(tf_MHD.getText());
		        				listHD.get(table.getSelectedRow()).setMaTour((String) comboBox_MaTour.getSelectedItem());
		        				listHD.get(table.getSelectedRow()).setMaKh((String) comboBox_MKH.getSelectedItem());
		        				tf_NgayLap.setText(String.valueOf(LocalDate.now()));
		        				listHD.get(table.getSelectedRow()).setNgayLap(tf_NgayLap.getText());
		        				if (RB1.isSelected())
		        					listHD.get(table.getSelectedRow()).setTrangThai("Đã thanh toán");
		        				else
		        					listHD.get(table.getSelectedRow()).setTrangThai("Chưa thanh toán");
		        				JOptionPane.showMessageDialog(dialog, "Sửa thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
		        				o.saveData(listHD, "dsHD.dat");
		        				setTable();
		        				dialog.setVisible(false);
		        			}
	        			}
	        			
	        		

	        }});
	    	
	    	dialog.setBackground(Color.blue);
	    	dialog.setVisible(true);
		}
		
		
    	

    	
		

	}
}
