package qltour.view;

import java.util.ArrayList;
import java.util.Comparator;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;
import qltour.check_loi.check_Loi;
import qltour.managedata.IO;
import qltour.model.KhachHang;
import qltour.model.Tour;

public class GuestJPanel extends javax.swing.JPanel {

    ArrayList<KhachHang> listKh = new ArrayList<>();
    static IO o = new IO();

    public GuestJPanel() {
        initComponents();
        setTable();
    }

    private void setTable() {
        DefaultTableModel defaultTableModel = new DefaultTableModel();
        KhachHang_jTable.setModel(defaultTableModel);
        ListSelectionModel listSelectionModel = KhachHang_jTable.getSelectionModel();
        listSelectionModel.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        defaultTableModel.addColumn("STT");
        defaultTableModel.addColumn("ID");
        defaultTableModel.addColumn("Tên Khách Hàng");
        defaultTableModel.addColumn("SĐT");
        defaultTableModel.addColumn("CMND/CCCD");
        defaultTableModel.addColumn("Quê Quán");
        defaultTableModel.addColumn("Giới Tính");
        defaultTableModel.addColumn("Email");
        defaultTableModel.addColumn("Ghi Chú");

        listKh = o.loadData(listKh, "dsKh.dat");
        int i = 0;
        for (KhachHang khachHang : listKh) {
            i++;
            defaultTableModel.addRow(new Object[]{i, khachHang.getID_client(), khachHang.getName_client(), khachHang.getPhone(), khachHang.getCMND(), khachHang.getHome_town(), khachHang.getSex(), khachHang.getEmail(), khachHang.getNotes()});
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        add_kh_jDialog = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        ID_jTextField = new javax.swing.JTextField();
        name_jTextField = new javax.swing.JTextField();
        std_jTextField = new javax.swing.JTextField();
        cmnd_jTextField = new javax.swing.JTextField();
        quequan_jTextField = new javax.swing.JTextField();
        add_jButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        note_jTextArea = new javax.swing.JTextArea();
        jLabel18 = new javax.swing.JLabel();
        email_jTextField = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        nam_jRadioButton = new javax.swing.JRadioButton();
        nu_jRadioButton = new javax.swing.JRadioButton();
        kh_jOptionPane = new javax.swing.JOptionPane();
        update_kh_jDialog = new javax.swing.JDialog();
        jPanel12 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        IDupdate_jTextField = new javax.swing.JTextField();
        nameupdate_jTextField1 = new javax.swing.JTextField();
        stdupdate_jTextField1 = new javax.swing.JTextField();
        cmndupdate_jTextField1 = new javax.swing.JTextField();
        quequanupdate_jTextField1 = new javax.swing.JTextField();
        update_jButton = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        noteupdate_jTextArea1 = new javax.swing.JTextArea();
        jLabel28 = new javax.swing.JLabel();
        emailupdate_jTextField1 = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        namupdate_jRadioButton1 = new javax.swing.JRadioButton();
        nuupdate_jRadioButton1 = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();
        ID_oldjTextField = new javax.swing.JTextField();
        sex_buttonGroup = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        KhachHang_jTable = new javax.swing.JTable();
        sort_kh_jComboBox = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        add_view_kh_jButton = new javax.swing.JButton();
        update_view_kh_jButton = new javax.swing.JButton();
        del_kh_jButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        Search_kh_jTextField = new javax.swing.JTextField();

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel5.setBackground(new java.awt.Color(207, 207, 207));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Thêm Khách Hàng");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 1033, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel4)
                .addGap(30, 30, 30))
        );

        jPanel1.add(jPanel5, java.awt.BorderLayout.PAGE_START);

        jPanel6.setBackground(new java.awt.Color(190, 223, 232));

        jPanel7.setBackground(new java.awt.Color(255, 255, 204));

        jLabel5.setText("ID Khách Hàng :");

        jLabel6.setText("Tên Khách Hàng :");

        jLabel7.setText("SĐT :");

        jLabel8.setText("CMND/CCCD: ");

        jLabel9.setText("Quê Quán");

        jLabel10.setText("Ghi Chú :");

        add_jButton.setBackground(new java.awt.Color(51, 153, 0));
        add_jButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        add_jButton.setForeground(new java.awt.Color(255, 255, 255));
        add_jButton.setText("Thêm");
        add_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_jButtonActionPerformed(evt);
            }
        });

        note_jTextArea.setColumns(20);
        note_jTextArea.setRows(5);
        jScrollPane2.setViewportView(note_jTextArea);

        jLabel18.setText("Email");

        jLabel20.setText("Giới Tính");

        sex_buttonGroup.add(nam_jRadioButton);
        nam_jRadioButton.setText("Nam");

        sex_buttonGroup.add(nu_jRadioButton);
        nu_jRadioButton.setText("Nữ");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(add_jButton))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                        .addGap(94, 94, 94)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(94, 94, 94)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(quequan_jTextField)
                            .addComponent(cmnd_jTextField)
                            .addComponent(std_jTextField)
                            .addComponent(ID_jTextField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(name_jTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE)
                            .addComponent(email_jTextField)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel7Layout.createSequentialGroup()
                                .addComponent(nam_jRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(43, 43, 43)
                                .addComponent(nu_jRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(82, 82, 82))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ID_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(20, 20, 20)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(name_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(20, 20, 20)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(std_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(20, 20, 20)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmnd_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(20, 20, 20)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(quequan_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(20, 20, 20)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addComponent(email_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel20))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nu_jRadioButton)
                            .addComponent(nam_jRadioButton))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addComponent(add_jButton)
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(231, Short.MAX_VALUE)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(230, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel6, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout add_kh_jDialogLayout = new javax.swing.GroupLayout(add_kh_jDialog.getContentPane());
        add_kh_jDialog.getContentPane().setLayout(add_kh_jDialogLayout);
        add_kh_jDialogLayout.setHorizontalGroup(
            add_kh_jDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        add_kh_jDialogLayout.setVerticalGroup(
            add_kh_jDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel12.setLayout(new java.awt.BorderLayout());

        jPanel13.setBackground(new java.awt.Color(207, 207, 207));

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("Cập Nhật Khách Hàng");

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, 1033, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel21)
                .addGap(30, 30, 30))
        );

        jPanel12.add(jPanel13, java.awt.BorderLayout.PAGE_START);

        jPanel14.setBackground(new java.awt.Color(190, 223, 232));

        jPanel15.setBackground(new java.awt.Color(255, 255, 204));

        jLabel22.setText("ID Khách Hàng mới :");

        jLabel23.setText("Tên Khách Hàng  :");

        jLabel24.setText("SĐT :");

        jLabel25.setText("CMND/CCCD: ");

        jLabel26.setText("Quê Quán");

        jLabel27.setText("Ghi Chú :");

        update_jButton.setBackground(new java.awt.Color(255, 204, 204));
        update_jButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        update_jButton.setText("Cập Nhật");
        update_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_jButtonActionPerformed(evt);
            }
        });

        noteupdate_jTextArea1.setColumns(20);
        noteupdate_jTextArea1.setRows(5);
        jScrollPane4.setViewportView(noteupdate_jTextArea1);

        jLabel28.setText("Email");

        jLabel29.setText("Giới Tính");

        sex_buttonGroup.add(namupdate_jRadioButton1);
        namupdate_jRadioButton1.setText("Nam");

        sex_buttonGroup.add(nuupdate_jRadioButton1);
        nuupdate_jRadioButton1.setText("Nữ");

        jLabel11.setText("ID Khách Hàng cũ:");

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel15Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(update_jButton))
                    .addGroup(jPanel15Layout.createSequentialGroup()
                        .addComponent(jLabel27, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                        .addGap(94, 94, 94)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel15Layout.createSequentialGroup()
                        .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel29, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel23, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel24, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel22, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel28, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(94, 94, 94)
                        .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(quequanupdate_jTextField1)
                            .addComponent(cmndupdate_jTextField1)
                            .addComponent(stdupdate_jTextField1)
                            .addComponent(IDupdate_jTextField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nameupdate_jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE)
                            .addComponent(emailupdate_jTextField1)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel15Layout.createSequentialGroup()
                                .addComponent(namupdate_jRadioButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(43, 43, 43)
                                .addComponent(nuupdate_jRadioButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(ID_oldjTextField, javax.swing.GroupLayout.Alignment.LEADING))))
                .addGap(82, 82, 82))
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(ID_oldjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IDupdate_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22))
                .addGap(20, 20, 20)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameupdate_jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23))
                .addGap(20, 20, 20)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stdupdate_jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24))
                .addGap(20, 20, 20)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmndupdate_jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25))
                .addGap(20, 20, 20)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(quequanupdate_jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26))
                .addGap(20, 20, 20)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel28)
                    .addComponent(emailupdate_jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel15Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel29))
                    .addGroup(jPanel15Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nuupdate_jRadioButton1)
                            .addComponent(namupdate_jRadioButton1))))
                .addGap(20, 20, 20)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27))
                .addGap(18, 18, 18)
                .addComponent(update_jButton)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                .addContainerGap(219, Short.MAX_VALUE)
                .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(218, Short.MAX_VALUE))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel12.add(jPanel14, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout update_kh_jDialogLayout = new javax.swing.GroupLayout(update_kh_jDialog.getContentPane());
        update_kh_jDialog.getContentPane().setLayout(update_kh_jDialogLayout);
        update_kh_jDialogLayout.setHorizontalGroup(
            update_kh_jDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        update_kh_jDialogLayout.setVerticalGroup(
            update_kh_jDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setBackground(new java.awt.Color(204, 255, 153));

        jPanel3.setBackground(new java.awt.Color(207, 207, 207));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Danh Sách Khách Hàng");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(190, 223, 232));

        KhachHang_jTable.setBackground(new java.awt.Color(255, 255, 204));
        KhachHang_jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(KhachHang_jTable);

        sort_kh_jComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ID", "Tên", "Quê Quán", "Giới Tính", "Email", " " }));
        sort_kh_jComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sort_kh_jComboBoxActionPerformed(evt);
            }
        });

        jLabel2.setText("Sort by:");

        add_view_kh_jButton.setBackground(new java.awt.Color(0, 102, 0));
        add_view_kh_jButton.setForeground(new java.awt.Color(255, 255, 255));
        add_view_kh_jButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qltour/images/add (1).png"))); // NOI18N
        add_view_kh_jButton.setText("Thêm");
        add_view_kh_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_view_kh_jButtonActionPerformed(evt);
            }
        });

        update_view_kh_jButton.setBackground(new java.awt.Color(255, 204, 204));
        update_view_kh_jButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qltour/images/edit-v2 (2).png"))); // NOI18N
        update_view_kh_jButton.setText("Sửa");
        update_view_kh_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_view_kh_jButtonActionPerformed(evt);
            }
        });

        del_kh_jButton.setBackground(new java.awt.Color(153, 51, 0));
        del_kh_jButton.setForeground(new java.awt.Color(255, 255, 255));
        del_kh_jButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qltour/images/rubbish-bin (1).png"))); // NOI18N
        del_kh_jButton.setText("Xóa");
        del_kh_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                del_kh_jButtonActionPerformed(evt);
            }
        });

        jLabel3.setText("Search");

        Search_kh_jTextField.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                Search_kh_jTextFieldCaretUpdate(evt);
            }
        });
        Search_kh_jTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Search_kh_jTextFieldActionPerformed(evt);
            }
        });
        Search_kh_jTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Search_kh_jTextFieldKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(Search_kh_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sort_kh_jComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 862, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(add_view_kh_jButton, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(update_view_kh_jButton, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(del_kh_jButton, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                    .addComponent(sort_kh_jComboBox, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3)
                    .addComponent(Search_kh_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(del_kh_jButton)
                    .addComponent(update_view_kh_jButton)
                    .addComponent(add_view_kh_jButton))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void sort_kh_jComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sort_kh_jComboBoxActionPerformed
        // TODO add your handling code here:
        String sortby = String.valueOf(sort_kh_jComboBox.getSelectedItem());
        if (sortby.equals("ID")) {
            listKh.sort(new Comparator<KhachHang>() {
                @Override
                public int compare(KhachHang o1, KhachHang o2) {
                    return o1.getID_client().compareTo(o2.getID_client());
                }
            });
        } else if (sortby.equals("Tên")) {
            listKh.sort(new Comparator<KhachHang>() {
                @Override
                public int compare(KhachHang o1, KhachHang o2) {
                    return o1.getName_client().compareTo(o2.getName_client());
                }
            });

        } else if (sortby.equals("Quê Quán")) {
            listKh.sort(new Comparator<KhachHang>() {
                @Override
                public int compare(KhachHang o1, KhachHang o2) {
                    return o1.getHome_town().compareTo(o2.getHome_town());
                }
            });
            
        }
        else if(sortby.equals("Giới Tính")){
            listKh.sort(new Comparator<KhachHang>() {
                @Override
                public int compare(KhachHang o1, KhachHang o2) {
                    return o1.getSex().compareTo(o2.getSex());
                }
            });
        }
        else {
            listKh.sort(new Comparator<KhachHang>() {
                @Override
                public int compare(KhachHang o1, KhachHang o2) {
                    return o1.getEmail().compareTo(o2.getEmail());
                }
            });
        }
        o.saveData(listKh, "dsKh.dat");
        setTable();
    }//GEN-LAST:event_sort_kh_jComboBoxActionPerformed

    private void add_view_kh_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_view_kh_jButtonActionPerformed
        // TODO add your handling code here:
        add_kh_jDialog.setSize(1000, 600);
        add_kh_jDialog.setVisible(true);
    }//GEN-LAST:event_add_view_kh_jButtonActionPerformed

    private void update_view_kh_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_view_kh_jButtonActionPerformed
        // TODO add your handling code here:
        update_kh_jDialog.setSize(1000, 600);
        update_kh_jDialog.setVisible(true);
    }//GEN-LAST:event_update_view_kh_jButtonActionPerformed

    private void del_kh_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_del_kh_jButtonActionPerformed
        // TODO add your handling code here:
        int removeIndex = KhachHang_jTable.getSelectedRow();
        if (removeIndex == -1) {
            kh_jOptionPane.showMessageDialog(update_kh_jDialog, "Vui lòng chọn dòng để xóa ", "Thông Báo", kh_jOptionPane.ERROR_MESSAGE);
        } else if (listKh.size() == 0) {
            kh_jOptionPane.showMessageDialog(update_kh_jDialog, "Bảng không có dữ liệu ", "Thông Báo", kh_jOptionPane.ERROR_MESSAGE);
        } else {
            listKh.remove(removeIndex);
            kh_jOptionPane.showMessageDialog(update_kh_jDialog, "Xóa thành công ", "Thông Báo", kh_jOptionPane.ERROR_MESSAGE);

        }
        o.saveData(listKh, "dsKh.dat");
        setTable();

    }//GEN-LAST:event_del_kh_jButtonActionPerformed

    private void Search_kh_jTextFieldCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_Search_kh_jTextFieldCaretUpdate
        // TODO add your handling code here:
    }//GEN-LAST:event_Search_kh_jTextFieldCaretUpdate

    private void Search_kh_jTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Search_kh_jTextFieldActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_Search_kh_jTextFieldActionPerformed

    private void Search_kh_jTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Search_kh_jTextFieldKeyReleased
        // TODO add your handling code here:
        ArrayList<KhachHang> searchKh = new ArrayList<>();
        String search_field = Search_kh_jTextField.getText();
        if (search_field.isEmpty()) {
            setTable();
        } else {
            for (KhachHang kh : listKh) {
                if (kh.getID_client().trim().toLowerCase().contains(search_field.trim().toLowerCase()) || kh.getName_client().trim().toLowerCase().contains(search_field.trim().toLowerCase()) || kh.getPhone().trim().toLowerCase().contains(search_field.trim().toLowerCase()) || kh.getCMND().toLowerCase().trim().contains(search_field.trim()) || kh.getSex().trim().toLowerCase().contains(search_field.trim().toLowerCase()) || kh.getHome_town().trim().toLowerCase().contains(search_field.trim().toLowerCase())) {
                    searchKh.add(kh);
                }
            }
            DefaultTableModel defaultTableModel = new DefaultTableModel();
            KhachHang_jTable.setModel(defaultTableModel);
            ListSelectionModel listSelectionModel = KhachHang_jTable.getSelectionModel();
            listSelectionModel.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
            defaultTableModel.addColumn("STT");
            defaultTableModel.addColumn("ID");
            defaultTableModel.addColumn("Tên Khách Hàng");
            defaultTableModel.addColumn("SĐT");
            defaultTableModel.addColumn("CMND/CCCD");
            defaultTableModel.addColumn("Quê Quán");
            defaultTableModel.addColumn("Giới Tính");
            defaultTableModel.addColumn("Email");
            defaultTableModel.addColumn("Ghi Chú");

            int i = 0;
            for (KhachHang khachHang : searchKh) {
                i++;
                defaultTableModel.addRow(new Object[]{i++, khachHang.getID_client(), khachHang.getName_client(), khachHang.getPhone(), khachHang.getCMND(), khachHang.getHome_town(), khachHang.getSex(), khachHang.getEmail(), khachHang.getNotes()});
            }

        }
    }//GEN-LAST:event_Search_kh_jTextFieldKeyReleased

    private void add_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_jButtonActionPerformed
        // TODO add your handling code here:
        listKh = o.loadData(listKh, "dsKh.dat");
        String CMND = cmnd_jTextField.getText();
        String ID = ID_jTextField.getText();
        String name = name_jTextField.getText();
        String sdt = std_jTextField.getText();
        String hometown = quequan_jTextField.getText();
        String note = note_jTextArea.getText();
        String email = email_jTextField.getText();
        String gender = "";
        if (nam_jRadioButton.isSelected()) {
            gender = "Nam";
        } else if (nu_jRadioButton.isSelected()) {
            gender = "Nữ";
        } else {
            kh_jOptionPane.showMessageDialog(add_kh_jDialog, "Vui lòng chọn giới tính ", "Thông Báo", kh_jOptionPane.ERROR_MESSAGE);

        }
        check_Loi n = new check_Loi();
        int checkID = n.erros_same_IDKH_v1(listKh, ID);
        if (ID.isEmpty()) {
            kh_jOptionPane.showMessageDialog(add_kh_jDialog, "ID không được rỗng   ", "Thông Báo", kh_jOptionPane.ERROR_MESSAGE);

        } else if (name.isEmpty()) {
            kh_jOptionPane.showMessageDialog(add_kh_jDialog, "Name không được rỗng   ", "Thông Báo", kh_jOptionPane.ERROR_MESSAGE);
        } else if (sdt.isEmpty()) {
            kh_jOptionPane.showMessageDialog(add_kh_jDialog, "SDT không được rỗng   ", "Thông Báo", kh_jOptionPane.ERROR_MESSAGE);
        } else if (checkID == 1) {
            kh_jOptionPane.showMessageDialog(add_kh_jDialog, "ID đã tồn tại   ", "Thông Báo", kh_jOptionPane.ERROR_MESSAGE);
        } else {
            KhachHang nkh = new KhachHang(ID, name, sdt, CMND, hometown, email, note, gender);
            listKh.add(nkh);
            kh_jOptionPane.showMessageDialog(add_kh_jDialog, "Thêm thành công ", "Thông Báo", kh_jOptionPane.INFORMATION_MESSAGE);

        }
        o.saveData(listKh, "dsKh.dat");

        setTable();
    }//GEN-LAST:event_add_jButtonActionPerformed

    private void update_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_jButtonActionPerformed
        // TODO add your handling code here:

        int count = 0;
        String idOld = ID_oldjTextField.getText();
        String idnew = IDupdate_jTextField.getText();
        String namenew = nameupdate_jTextField1.getText();
        String sdt = stdupdate_jTextField1.getText();
        String cmnd = cmndupdate_jTextField1.getText();
        String hometown = quequanupdate_jTextField1.getText();
        String email = emailupdate_jTextField1.getText();
        String gender = "";
        if (namupdate_jRadioButton1.isSelected()) {
            gender = "Nam";
        } else if (nuupdate_jRadioButton1.isSelected()) {
            gender = "Nữ";
        } else {
            kh_jOptionPane.showMessageDialog(add_kh_jDialog, "Vui lòng chọn giới tính ", "Thông Báo", kh_jOptionPane.ERROR_MESSAGE);

        }
        String note = noteupdate_jTextArea1.getText();
        check_Loi n = new check_Loi();
//        Tour newtour = new Tour(idnew, namenew, note, pricenew, namenew, des);
        int checkID = n.erros_same_IDKH_v2(listKh, idnew, idOld);
        if (idOld.isEmpty()) {
            kh_jOptionPane.showMessageDialog(update_kh_jDialog, "ID_old không được rỗng   ", "Thông Báo", kh_jOptionPane.ERROR_MESSAGE);

        } else if (idnew.isEmpty()) {
            kh_jOptionPane.showMessageDialog(update_kh_jDialog, "ID_new không được rỗng   ", "Thông Báo", kh_jOptionPane.ERROR_MESSAGE);
        } else if (namenew.isEmpty()) {
            kh_jOptionPane.showMessageDialog(update_kh_jDialog, "Name không được rỗng   ", "Thông Báo", kh_jOptionPane.ERROR_MESSAGE);
        } else if (sdt.isEmpty()) {
            kh_jOptionPane.showMessageDialog(update_kh_jDialog, "SĐT không được rỗng   ", "Thông Báo", kh_jOptionPane.ERROR_MESSAGE);
        } else if (cmnd.isEmpty()) {
            kh_jOptionPane.showMessageDialog(update_kh_jDialog, "CMND/CCCD không được rỗng   ", "Thông Báo", kh_jOptionPane.ERROR_MESSAGE);
        } else if (email.isEmpty()) {
            kh_jOptionPane.showMessageDialog(update_kh_jDialog, "Email không được rỗng   ", "Thông Báo", kh_jOptionPane.ERROR_MESSAGE);
        } else if (checkID == 1) {
            kh_jOptionPane.showMessageDialog(update_kh_jDialog, "ID đã tồn tại ", "Thông Báo", kh_jOptionPane.ERROR_MESSAGE);
        } else {
            for (KhachHang khachHang : listKh) {
                if (khachHang.getID_client().trim().toLowerCase().equals(idOld.trim().toLowerCase())) {
                    count++;
                    khachHang.setID_client(idnew);
                    khachHang.setName_client(namenew);
                    khachHang.setPhone(sdt);
                    khachHang.setCMND(cmnd);
                    khachHang.setHome_town(hometown);
                    khachHang.setEmail(email);
                    khachHang.setSex(gender);
                    khachHang.setNotes(note);
                }
            }
            if (count == 0) {
                kh_jOptionPane.showMessageDialog(update_kh_jDialog, "ID_old không tồn tại trong danh sách ", "Thông Báo", kh_jOptionPane.ERROR_MESSAGE);
            } else {
                kh_jOptionPane.showMessageDialog(update_kh_jDialog, "Cập nhật thành công ", "Thông Báo", kh_jOptionPane.INFORMATION_MESSAGE);
            }
            o.saveData(listKh, "dsKh.dat");
            setTable();
        }

    }//GEN-LAST:event_update_jButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ID_jTextField;
    private javax.swing.JTextField ID_oldjTextField;
    private javax.swing.JTextField IDupdate_jTextField;
    private javax.swing.JTable KhachHang_jTable;
    private javax.swing.JTextField Search_kh_jTextField;
    private javax.swing.JButton add_jButton;
    private javax.swing.JDialog add_kh_jDialog;
    private javax.swing.JButton add_view_kh_jButton;
    private javax.swing.JTextField cmnd_jTextField;
    private javax.swing.JTextField cmndupdate_jTextField1;
    private javax.swing.JButton del_kh_jButton;
    private javax.swing.JTextField email_jTextField;
    private javax.swing.JTextField emailupdate_jTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JOptionPane kh_jOptionPane;
    private javax.swing.JRadioButton nam_jRadioButton;
    private javax.swing.JTextField name_jTextField;
    private javax.swing.JTextField nameupdate_jTextField1;
    private javax.swing.JRadioButton namupdate_jRadioButton1;
    private javax.swing.JTextArea note_jTextArea;
    private javax.swing.JTextArea noteupdate_jTextArea1;
    private javax.swing.JRadioButton nu_jRadioButton;
    private javax.swing.JRadioButton nuupdate_jRadioButton1;
    private javax.swing.JTextField quequan_jTextField;
    private javax.swing.JTextField quequanupdate_jTextField1;
    private javax.swing.ButtonGroup sex_buttonGroup;
    private javax.swing.JComboBox<String> sort_kh_jComboBox;
    private javax.swing.JTextField std_jTextField;
    private javax.swing.JTextField stdupdate_jTextField1;
    private javax.swing.JButton update_jButton;
    private javax.swing.JDialog update_kh_jDialog;
    private javax.swing.JButton update_view_kh_jButton;
    // End of variables declaration//GEN-END:variables
}
