
package qltour.view;

import com.toedter.calendar.JDateChooser;
import java.io.Serializable;
import java.util.Date;
import java.text.SimpleDateFormat;
import java.text.DateFormat;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Comparator;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;
import qltour.check_loi.check_Loi;
import qltour.managedata.IO;
import qltour.model.KhachHang;
import qltour.model.LichTrinh;
import qltour.model.Tour;


public class LichTrinhJPanel extends javax.swing.JPanel implements Serializable {
    
     ArrayList<LichTrinh> listLT =  new ArrayList<>();           
     ArrayList<KhachHang> K = new ArrayList<>();
     ArrayList<Tour> T = new ArrayList<>();
            
     static IO o= new IO();
        
    public LichTrinhJPanel() {
        initComponents();
        showDatacomboBox();
        showDatacomboBox1();
        chua.setSelected(true);
        
        setTable1();
    }

    
     private  void showDatacomboBox(){
        K= o.loadData(K, "dsKh.dat");
        T= o.loadData(T, "dsTour1.dat");
        for (KhachHang ks :K ) {
            tenkh_jComboBox1.addItem(ks.getID_client());
        }
        for (Tour tt : T) {
            tentour_jComboBox2.addItem(tt.getID_Tour());
            
        }
    }
      private  void showDatacomboBox1(){
        K= o.loadData(K, "dsKh.dat");
        T= o.loadData(T, "dsTour1.dat");
        for (KhachHang ks :K ) {
            KH_jComboBox1.addItem(ks.getID_client());
        }
        for (Tour tt : T) {
            Tour_jComboBox2.addItem(tt.getID_Tour());
            
        }
    }
    private void setTable1() {
        
        DefaultTableModel defaultTableModel = new DefaultTableModel();
        Lichtrinh_jTable.setModel(defaultTableModel);
        ListSelectionModel listSelectionModel = Lichtrinh_jTable.getSelectionModel();
        listSelectionModel.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        defaultTableModel.addColumn("STT");
        defaultTableModel.addColumn("ID ");
        defaultTableModel.addColumn("Khách hàng");
        defaultTableModel.addColumn("Tour");
        defaultTableModel.addColumn("Ngày bắt đầu");
        defaultTableModel.addColumn("Ngày kết thúc");
        defaultTableModel.addColumn("Số khách");
        defaultTableModel.addColumn("HDV");
        defaultTableModel.addColumn("Trạng thái");
        
        listLT = o.loadData(listLT, "dsLT.dat");
        int i=0 ;
        for (LichTrinh lichTrinh : listLT) {
            i++;
            defaultTableModel.addRow(new Object[]{i, lichTrinh.getID_lichTrinh(),lichTrinh.getKh(),lichTrinh.getTour(),lichTrinh.getDate_start(),lichTrinh.getDate_end(),lichTrinh.getSoKhach(),lichTrinh.getHDV(),lichTrinh.getTrangThai()});
        }
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        add_lt = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        id_licht = new javax.swing.JTextField();
        sokhach = new javax.swing.JTextField();
        HDV_DL = new javax.swing.JTextField();
        chua = new javax.swing.JRadioButton();
        dang = new javax.swing.JRadioButton();
        kt = new javax.swing.JRadioButton();
        them = new javax.swing.JButton();
        KHACHH = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        NBD = new com.toedter.calendar.JDateChooser();
        NKTt = new com.toedter.calendar.JDateChooser();
        tenkh_jComboBox1 = new javax.swing.JComboBox<>();
        tentour_jComboBox2 = new javax.swing.JComboBox<>();
        update_m = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        id_moi = new javax.swing.JTextField();
        soluog = new javax.swing.JTextField();
        tenHDV = new javax.swing.JTextField();
        c = new javax.swing.JRadioButton();
        d = new javax.swing.JRadioButton();
        dd = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        id_cu = new javax.swing.JTextField();
        capnhat = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        ngaybdd = new com.toedter.calendar.JDateChooser();
        ngayktt = new com.toedter.calendar.JDateChooser();
        KH_jComboBox1 = new javax.swing.JComboBox<>();
        Tour_jComboBox2 = new javax.swing.JComboBox<>();
        kk_jOptionPane1 = new javax.swing.JOptionPane();
        add_viewlt = new javax.swing.JButton();
        xoa_lt = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        iteam = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        Lichtrinh_jTable = new javax.swing.JTable();
        Search_lt_jTextField = new javax.swing.JTextField();
        sua_li = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(255, 204, 153));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("ID Lịch Trình");

        jLabel6.setBackground(new java.awt.Color(255, 153, 153));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setText("Thêm Lịch Trình");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Ngày Bắt Đầu");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("Ngày Kết Thúc");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("Số Lượng Khách");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setText("Hướng Dẫn Viên ");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setText("Trạng Thái");

        id_licht.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id_lichtActionPerformed(evt);
            }
        });

        buttonGroup1.add(chua);
        chua.setText("Chưa bắt đầu");
        chua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chuaActionPerformed(evt);
            }
        });

        buttonGroup1.add(dang);
        dang.setText("Đang diễn ra");
        dang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dangActionPerformed(evt);
            }
        });

        buttonGroup1.add(kt);
        kt.setText("Kết Thúc");
        kt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ktActionPerformed(evt);
            }
        });

        them.setBackground(new java.awt.Color(51, 153, 0));
        them.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        them.setForeground(new java.awt.Color(255, 255, 255));
        them.setText("Thêm");
        them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                themActionPerformed(evt);
            }
        });

        KHACHH.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        KHACHH.setText("Khách Hàng");

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel20.setText("Tour");

        tenkh_jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tenkh_jComboBox1ActionPerformed(evt);
            }
        });

        tentour_jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tentour_jComboBox2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(KHACHH, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                                .addGap(4, 4, 4)))
                        .addGap(91, 91, 91))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(them)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(NKTt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(NBD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(chua, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(dang, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(kt, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(HDV_DL)
                        .addComponent(sokhach)
                        .addComponent(id_licht)
                        .addComponent(tenkh_jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tentour_jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(168, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(29, 29, 29)
                                        .addComponent(jLabel6)
                                        .addGap(59, 59, 59)
                                        .addComponent(id_licht, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(126, 126, 126)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(KHACHH, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tenkh_jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(15, 15, 15)
                                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(tentour_jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addComponent(NBD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(256, 256, 256)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(NKTt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(jLabel8)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sokhach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HDV_DL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chua)
                    .addComponent(dang)
                    .addComponent(kt))
                .addGap(18, 18, 18)
                .addComponent(them)
                .addContainerGap())
        );

        javax.swing.GroupLayout add_ltLayout = new javax.swing.GroupLayout(add_lt.getContentPane());
        add_lt.getContentPane().setLayout(add_ltLayout);
        add_ltLayout.setHorizontalGroup(
            add_ltLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(add_ltLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        add_ltLayout.setVerticalGroup(
            add_ltLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(255, 204, 153));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setText("ID Mới");

        jLabel13.setBackground(new java.awt.Color(255, 153, 153));
        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Sửa Lịch Trình");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setText("Ngày Bắt Đầu");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel15.setText("Ngày Kết Thúc");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel16.setText("Số Khách");

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel17.setText("Hướng Dẫn Viên");

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel18.setText("Trangj Thái");

        id_moi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id_moiActionPerformed(evt);
            }
        });

        soluog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                soluogActionPerformed(evt);
            }
        });

        buttonGroup1.add(c);
        c.setText("Chưa bắt đầu");
        c.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cActionPerformed(evt);
            }
        });

        buttonGroup1.add(d);
        d.setText("Đang diễn ra ");

        buttonGroup1.add(dd);
        dd.setText("Kết thúc");
        dd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ddActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("ID Cũ");

        id_cu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id_cuActionPerformed(evt);
            }
        });

        capnhat.setBackground(new java.awt.Color(255, 204, 204));
        capnhat.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        capnhat.setText("Cập Nhật");
        capnhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                capnhatActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel19.setText("Khách Hàng");

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel21.setText("Tour");

        KH_jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KH_jComboBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(215, 215, 215)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(soluog, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(tenHDV, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(c, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(d, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(dd, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(capnhat))
                                .addContainerGap(93, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(ngaybdd, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                                    .addComponent(ngayktt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                                .addComponent(jLabel1)
                                .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(215, 215, 215)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(id_moi, javax.swing.GroupLayout.DEFAULT_SIZE, 333, Short.MAX_VALUE)
                            .addComponent(id_cu)
                            .addComponent(KH_jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Tour_jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(221, 221, 221)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(jLabel1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel13)
                        .addGap(34, 34, 34)
                        .addComponent(id_cu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel12)
                    .addComponent(id_moi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(KH_jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Tour_jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel14))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ngaybdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel15)
                    .addComponent(ngayktt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(soluog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tenHDV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(c)
                        .addComponent(d)
                        .addComponent(dd)))
                .addGap(32, 32, 32)
                .addComponent(capnhat)
                .addContainerGap(81, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout update_mLayout = new javax.swing.GroupLayout(update_m.getContentPane());
        update_m.getContentPane().setLayout(update_mLayout);
        update_mLayout.setHorizontalGroup(
            update_mLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(update_mLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        update_mLayout.setVerticalGroup(
            update_mLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(update_mLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        setBackground(new java.awt.Color(190, 223, 232));
        setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N

        add_viewlt.setBackground(new java.awt.Color(51, 153, 0));
        add_viewlt.setForeground(new java.awt.Color(255, 255, 255));
        add_viewlt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qltour/images/add (1).png"))); // NOI18N
        add_viewlt.setText("Thêm ");
        add_viewlt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_viewltActionPerformed(evt);
            }
        });

        xoa_lt.setBackground(new java.awt.Color(204, 51, 0));
        xoa_lt.setForeground(new java.awt.Color(255, 255, 255));
        xoa_lt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qltour/images/rubbish-bin (1).png"))); // NOI18N
        xoa_lt.setText("Xóa");
        xoa_lt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xoa_ltActionPerformed(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(255, 255, 51));
        jLabel3.setText("Search");

        jLabel4.setText("Sort bt:");

        iteam.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ID", "Tour", "HDV", " " }));
        iteam.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                iteamItemStateChanged(evt);
            }
        });
        iteam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iteamActionPerformed(evt);
            }
        });

        Lichtrinh_jTable.setBackground(new java.awt.Color(255, 255, 204));
        Lichtrinh_jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "STT", "ID ", "Khách Hàng", "Tour", "Ngày bắt đầu", "Ngày kết thúc", "Số Lượng", "Hướng dẫn viên ", "Trạng thái"
            }
        ));
        jScrollPane1.setViewportView(Lichtrinh_jTable);

        Search_lt_jTextField.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                Search_lt_jTextFieldCaretUpdate(evt);
            }
        });
        Search_lt_jTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Search_lt_jTextFieldActionPerformed(evt);
            }
        });
        Search_lt_jTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Search_lt_jTextFieldKeyReleased(evt);
            }
        });

        sua_li.setBackground(new java.awt.Color(255, 204, 204));
        sua_li.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qltour/images/edit-v2 (2).png"))); // NOI18N
        sua_li.setText("Sửa");
        sua_li.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sua_liActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(207, 207, 207));

        jLabel22.setBackground(new java.awt.Color(255, 255, 255));
        jLabel22.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("Danh Sách Lịch Trình");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(add_viewlt)
                .addGap(50, 50, 50)
                .addComponent(sua_li)
                .addGap(50, 50, 50)
                .addComponent(xoa_lt)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Search_lt_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 402, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(iteam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Search_lt_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(iteam, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                        .addGap(7, 7, 7)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 323, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(add_viewlt)
                    .addComponent(sua_li)
                    .addComponent(xoa_lt))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void add_viewltActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_viewltActionPerformed
        // TODO add your handling code here:
        
        add_lt.setSize(1000,600);
        add_lt.setVisible(true);
        
    }//GEN-LAST:event_add_viewltActionPerformed

    private void iteamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iteamActionPerformed
        // TODO add your handling code here:
        
        
        String sortby = String.valueOf(iteam.getSelectedItem());
        if (sortby.equals("ID")) {
            listLT.sort(new Comparator<LichTrinh>() {
                @Override
                public int compare(LichTrinh o1, LichTrinh o2) {
                    return o1.getID_lichTrinh().compareTo(o2.getID_lichTrinh());
                }
            });
        }
        else if (sortby.equals("Name tour")) {
            listLT.sort(new Comparator<LichTrinh>() {
                @Override
                public int compare(LichTrinh o1, LichTrinh o2) {
                    return o1.getTour().compareTo(o2.getTour());
                }
            });

        } 
        else {
            listLT.sort(new Comparator<LichTrinh>() {
                @Override
                public int compare(LichTrinh o1, LichTrinh o2) {
                    return o1.getHDV().compareTo(o2.getHDV());
                }
            });
        }
            
        o.saveData(listLT, "dsLT.dat");
        setTable1();
        
        
    }//GEN-LAST:event_iteamActionPerformed

    private void iteamItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_iteamItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_iteamItemStateChanged

    private void chuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chuaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chuaActionPerformed

    private void id_lichtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id_lichtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_id_lichtActionPerformed

    private void themActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_themActionPerformed
        // TODO add your handling code here:
        listLT = o.loadData(listLT, "dsLT.dat");
        DateFormat dataformat = null;
        Tour t = new Tour();
        KhachHang kh = new KhachHang();
        Date date1 = NBD.getDate();
        dataformat = new SimpleDateFormat("MM/dd/yyyy");
        Date date2 = NKTt.getDate();
        t.setID_Tour((String) tentour_jComboBox2.getSelectedItem());
        String idtour = t.getID_Tour();
        kh.setID_client((String) tenkh_jComboBox1.getSelectedItem());
        String idkh = kh.getID_client();
        String ID = id_licht.getText();
        String HDV = HDV_DL.getText();
        double solg = 0;
        boolean solginput = false;
        while (!solginput) {
            try {
                solg = Double.parseDouble(sokhach.getText());
                solginput = true;
            } catch (NumberFormatException e) {
                e.getMessage();
                kk_jOptionPane1.showMessageDialog(add_lt, "Price must be number ", "Thông Báo", kk_jOptionPane1.ERROR_MESSAGE);
                break;
            }

        }
        SimpleDateFormat formatter = new SimpleDateFormat("MM/dd/yyyy");
        String kttg= formatter.format(date1);
        String trangthai= "";
        if (chua.isSelected()) {
            trangthai = "Chưa bắt đầu ";
        } else if (dang.isSelected()) {
            trangthai = "Đang diễn ra ";
        } else if (kt.isSelected()){
            trangthai= " Kết thúc";           
        }
        else {
            kk_jOptionPane1.showMessageDialog(add_lt, "Vui lòng chọn trạng thai ", "Thông Báo", kk_jOptionPane1.ERROR_MESSAGE);
        }
        
        check_Loi n = new check_Loi();
        int checkID = n.erros_same_IDLT_v1(listLT, ID);
        int checkID1 = n.erros_same_IDLT_v3(listLT, kttg);
        if (ID.isEmpty()) {
            kk_jOptionPane1.showMessageDialog(add_lt, "ID không được rỗng   ", "Thông Báo", kk_jOptionPane1.ERROR_MESSAGE);
        
        }else 
            if(HDV.isEmpty()){
            kk_jOptionPane1.showMessageDialog(add_lt, "HDV không được rỗng   ", "Thông Báo", kk_jOptionPane1.ERROR_MESSAGE);
        }else
            if (checkID == 1) {
            kk_jOptionPane1.showMessageDialog(add_lt, "ID đã tồn tại   ", "Thông Báo", kk_jOptionPane1.ERROR_MESSAGE);
        } else 
                if (checkID1  == 1){
                    kk_jOptionPane1.showMessageDialog(add_lt, "Bạn bị trùng lịch ", "Thông Báo", kk_jOptionPane1.ERROR_MESSAGE);
        
                }
            
            else {
                    LichTrinh nlt = new LichTrinh(ID, idkh, idtour, kttg, kttg, solg, HDV, trangthai);
                    listLT.add(nlt);
            kk_jOptionPane1.showMessageDialog(add_lt, "Thêm thành công ", "Thông Báo", kk_jOptionPane1.INFORMATION_MESSAGE);
            
        }
        
        o.saveData(listLT, "dsLT.dat");
        setTable1();
        
    }//GEN-LAST:event_themActionPerformed

    private void xoa_ltActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xoa_ltActionPerformed
        // TODO add your handling code here:
        int removeIndex = Lichtrinh_jTable.getSelectedRow();
        if (removeIndex == -1) {
            kk_jOptionPane1.showMessageDialog(update_m, "Vui lòng chọn dòng để xóa ", "Thông Báo", kk_jOptionPane1.ERROR_MESSAGE);
        } else if (listLT.size() == 0) {
            kk_jOptionPane1.showMessageDialog(update_m, "Bảng không có dữ liệu ", "Thông Báo", kk_jOptionPane1.ERROR_MESSAGE);
        } else {
            listLT.remove(removeIndex);
            kk_jOptionPane1.showMessageDialog(update_m, "Xóa thành công ", "Thông Báo", kk_jOptionPane1.ERROR_MESSAGE);

        }
        o.saveData(listLT, "dsLT.dat");
        setTable1();
    }//GEN-LAST:event_xoa_ltActionPerformed

    private void Search_lt_jTextFieldCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_Search_lt_jTextFieldCaretUpdate
        // TODO add your handling code here:
    }//GEN-LAST:event_Search_lt_jTextFieldCaretUpdate

    private void Search_lt_jTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Search_lt_jTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Search_lt_jTextFieldActionPerformed

    private void Search_lt_jTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Search_lt_jTextFieldKeyReleased
        // TODO add your handling code here:
        ArrayList<LichTrinh> searchlt = new ArrayList<>();
        String search_field = Search_lt_jTextField.getText();
        if (search_field.isEmpty()) {
            setTable1();
        } else {
            for (LichTrinh lt : listLT) {
                if (lt.getID_lichTrinh().trim().toLowerCase().contains(search_field.trim().toLowerCase()) || lt.getTour().trim().toLowerCase().contains(search_field.trim().toLowerCase()) || lt.getHDV().trim().toLowerCase().contains(search_field.trim().toLowerCase()) || lt.getKh().trim().toLowerCase().trim().contains(search_field.trim()) || lt.getTrangThai().trim().toLowerCase().contains(search_field.trim().toLowerCase())) {
                    searchlt.add(lt);
                }
            }
            DefaultTableModel defaultTableModel = new DefaultTableModel();
            Lichtrinh_jTable.setModel(defaultTableModel);
            ListSelectionModel listSelectionModel = Lichtrinh_jTable.getSelectionModel();
            listSelectionModel.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
            defaultTableModel.addColumn("STT");
            defaultTableModel.addColumn("ID");
            defaultTableModel.addColumn("Khách Hàng");
            defaultTableModel.addColumn("Tour");
            defaultTableModel.addColumn("Ngày bắt đầu");
            defaultTableModel.addColumn("Ngày kết thúc");
            defaultTableModel.addColumn("Số lượng");
            defaultTableModel.addColumn("HDV");
            defaultTableModel.addColumn("Trạng thái");

            int i = 0;
            for (LichTrinh lichTrinh: searchlt) {
                i++;
            defaultTableModel.addRow(new Object[]{i++, lichTrinh.getID_lichTrinh(),lichTrinh.getKh(),lichTrinh.getTour(),lichTrinh.getDate_start(),lichTrinh.getDate_end(),lichTrinh.getSoKhach(),lichTrinh.getHDV(),lichTrinh.getTrangThai()});
            }

        }
    }//GEN-LAST:event_Search_lt_jTextFieldKeyReleased

    private void sua_liActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sua_liActionPerformed
        // TODO add your handling code here:
        update_m.setSize(1000,600);
        update_m.setVisible(true);
    }//GEN-LAST:event_sua_liActionPerformed

    private void capnhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_capnhatActionPerformed
        // TODO add your handling code here:
       KhachHang kh = new KhachHang();
       Tour t = new Tour();
        int count =0 ;
        DateFormat dataformat = null;
        dataformat = new SimpleDateFormat("MM/dd/yyyy");
        kh.setID_client((String) KH_jComboBox1.getSelectedItem());
        String idkh = kh.getID_client();
        t.setID_Tour((String) Tour_jComboBox2.getSelectedItem());
        String idtour=t.getID_Tour();
        Date date = ngaybdd.getDate();
        Date date3 = ngayktt.getDate();
        String ID_new = id_moi.getText();
        String ID_old = id_cu.getText();
        String HDVd = tenHDV.getText();
        double solg = 0;
        boolean solginput = false;
        while (!solginput) {
            try {
                solg = Double.parseDouble(sokhach.getText());
                solginput = true;
            } catch (NumberFormatException e) {
                e.getMessage();
                kk_jOptionPane1.showMessageDialog(add_lt, "so luong  must be number ", "Thông Báo", kk_jOptionPane1.ERROR_MESSAGE);
                break;
            }

        }
        String trangThai= "";
        if (c.isSelected()) {
            trangThai = "chưa bắt đầu ";
        } else if (d.isSelected()) {
            trangThai = "đang diễn ra";
        } else if (dd.isSelected()){
            trangThai= "kết thúc";
        }
        else {
            kk_jOptionPane1.showMessageDialog(update_m, "Vui lòng chọn trang thai ", "Thông Báo", kk_jOptionPane1.ERROR_MESSAGE);

        }
        check_Loi n = new check_Loi();
        int checkID = n.erros_same_IDLT_v2(listLT, ID_new,ID_old);
        if (ID_new.isEmpty()) {
            kk_jOptionPane1.showMessageDialog(update_m, "ID không được rỗng   ", "Thông Báo", kk_jOptionPane1.ERROR_MESSAGE);

        } else
        if (ID_old.isEmpty()) {
            kk_jOptionPane1.showMessageDialog(update_m, "ID không được rỗng   ", "Thông Báo", kk_jOptionPane1.ERROR_MESSAGE);

        
        }else if(HDVd.isEmpty()){
            kk_jOptionPane1.showMessageDialog(update_m, "HDV không được rỗng   ", "Thông Báo", kk_jOptionPane1.ERROR_MESSAGE);
        }else
        if (checkID == 1) {
            kk_jOptionPane1.showMessageDialog(update_m, "ID đã tồn tại   ", "Thông Báo", kk_jOptionPane1.ERROR_MESSAGE);
        } else {
            for (LichTrinh lt : listLT){
                if (lt.getID_lichTrinh().trim().toLowerCase().equals(ID_old.trim().toLowerCase())) {
                    count++;
                    lt.setID_lichTrinh(ID_new);
                    lt.setKh(idkh);
                    lt.setTour(idtour);
                    lt.setDate_start(dataformat.format(date));
                    lt.setDate_end(dataformat.format(date3));
                    lt.setSoKhach(solg);
                    lt.setHDV(HDVd);
                    lt.setTrangThai(trangThai);

                }
            }
            if (count == 0) {
                kk_jOptionPane1.showMessageDialog(update_m, "ID_old không tồn tại ", "Thông Báo", kk_jOptionPane1.ERROR_MESSAGE);
            } else {
                kk_jOptionPane1.showMessageDialog(update_m, "Cập nhật thành công ", "Thông Báo", kk_jOptionPane1.INFORMATION_MESSAGE);
            }

            o.saveData(listLT, "dsLT.dat");
            setTable1();
     }
        
    }//GEN-LAST:event_capnhatActionPerformed

    private void id_cuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id_cuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_id_cuActionPerformed

    private void cActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cActionPerformed

    private void soluogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_soluogActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_soluogActionPerformed

    private void id_moiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id_moiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_id_moiActionPerformed

    private void tenkh_jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tenkh_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tenkh_jComboBox1ActionPerformed

    private void dangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dangActionPerformed

    private void ktActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ktActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ktActionPerformed

    private void ddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ddActionPerformed

    private void tentour_jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tentour_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tentour_jComboBox2ActionPerformed

    private void KH_jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KH_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_KH_jComboBox1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField HDV_DL;
    private javax.swing.JLabel KHACHH;
    private javax.swing.JComboBox<String> KH_jComboBox1;
    private javax.swing.JTable Lichtrinh_jTable;
    private com.toedter.calendar.JDateChooser NBD;
    private com.toedter.calendar.JDateChooser NKTt;
    private javax.swing.JTextField Search_lt_jTextField;
    private javax.swing.JComboBox<String> Tour_jComboBox2;
    private javax.swing.JDialog add_lt;
    private javax.swing.JButton add_viewlt;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton c;
    private javax.swing.JButton capnhat;
    private javax.swing.JRadioButton chua;
    private javax.swing.JRadioButton d;
    private javax.swing.JRadioButton dang;
    private javax.swing.JRadioButton dd;
    private javax.swing.JTextField id_cu;
    private javax.swing.JTextField id_licht;
    private javax.swing.JTextField id_moi;
    private javax.swing.JComboBox<String> iteam;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JOptionPane kk_jOptionPane1;
    private javax.swing.JRadioButton kt;
    private com.toedter.calendar.JDateChooser ngaybdd;
    private com.toedter.calendar.JDateChooser ngayktt;
    private javax.swing.JTextField sokhach;
    private javax.swing.JTextField soluog;
    private javax.swing.JButton sua_li;
    private javax.swing.JTextField tenHDV;
    private javax.swing.JComboBox<String> tenkh_jComboBox1;
    private javax.swing.JComboBox<String> tentour_jComboBox2;
    private javax.swing.JButton them;
    private javax.swing.JDialog update_m;
    private javax.swing.JButton xoa_lt;
    // End of variables declaration//GEN-END:variables
}
