
package qltour.view;

import java.io.Serializable;
import java.time.LocalDate;

import java.util.ArrayList;
import java.util.Comparator;
import javax.swing.ListSelectionModel;

import javax.swing.table.DefaultTableModel;
import qltour.check_loi.check_Loi;
import qltour.managedata.IO;
import qltour.model.Tour;

public class TourJPanel extends javax.swing.JPanel implements Serializable {

    ArrayList<Tour> listTour = new ArrayList<>();
    static IO o = new IO();

    public TourJPanel() {
        initComponents();
        setTable();
    }

    private void setTable() {
        DefaultTableModel defaultTableModel = new DefaultTableModel();
        Tour_jTable.setModel(defaultTableModel);
        ListSelectionModel listSelectionModel = Tour_jTable.getSelectionModel();
        listSelectionModel.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        defaultTableModel.addColumn("STT");
        defaultTableModel.addColumn("ID");
        defaultTableModel.addColumn("Ten Tour");
        defaultTableModel.addColumn("Ngày Tạo");
        defaultTableModel.addColumn("Điểm Đến");
        defaultTableModel.addColumn("Giá");
        defaultTableModel.addColumn("Ghi Chú");
        listTour = o.loadData(listTour, "dsTour1.dat");
        int i = 0;
        for (Tour tour : listTour) {
            i++;
            defaultTableModel.addRow(new Object[]{i, tour.getID_Tour(), tour.getName_Tour(), tour.getDate_create(), tour.getDestination(), tour.getPrice_Tour(), tour.getNote()});
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        add_tour_jDialog = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        ID_jTextField = new javax.swing.JTextField();
        name_jTextField = new javax.swing.JTextField();
        price_jTextField = new javax.swing.JTextField();
        date_jTextField = new javax.swing.JTextField();
        des_jTextField = new javax.swing.JTextField();
        add_jButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        note_jTextArea = new javax.swing.JTextArea();
        Tour_jOptionPane = new javax.swing.JOptionPane();
        update_tour_jDialog = new javax.swing.JDialog();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        ID_old_jTextField = new javax.swing.JTextField();
        name_update_jTextField = new javax.swing.JTextField();
        price_update_jTextField = new javax.swing.JTextField();
        date_update_jTextField = new javax.swing.JTextField();
        des_update_jTextField = new javax.swing.JTextField();
        update_jButton1 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        note_update_jTextArea = new javax.swing.JTextArea();
        jLabel19 = new javax.swing.JLabel();
        ID_update_jTextField = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tour_jTable = new javax.swing.JTable();
        sort_jComboBox = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        add_view_jButton = new javax.swing.JButton();
        update_view_jButton = new javax.swing.JButton();
        del_jButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        Search_jTextField = new javax.swing.JTextField();

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel5.setBackground(new java.awt.Color(207, 207, 207));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Thêm Tour Du Lịch");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 1033, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel4)
                .addGap(30, 30, 30))
        );

        jPanel1.add(jPanel5, java.awt.BorderLayout.PAGE_START);

        jPanel6.setBackground(new java.awt.Color(190, 223, 232));

        jPanel7.setBackground(new java.awt.Color(255, 255, 204));

        jLabel5.setText("ID Tour :");

        jLabel6.setText("Tên Tour :");

        jLabel7.setText("Giá Tour :");

        jLabel8.setText("Ngày Tạo :");

        jLabel9.setText("Điểm Đến :");

        jLabel10.setText("Ghi Chú :");

        add_jButton.setBackground(new java.awt.Color(0, 153, 51));
        add_jButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        add_jButton.setForeground(new java.awt.Color(255, 255, 255));
        add_jButton.setText("Thêm");
        add_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_jButtonActionPerformed(evt);
            }
        });

        note_jTextArea.setColumns(20);
        note_jTextArea.setRows(5);
        jScrollPane2.setViewportView(note_jTextArea);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(94, 94, 94)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(add_jButton)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(des_jTextField)
                            .addComponent(date_jTextField)
                            .addComponent(price_jTextField)
                            .addComponent(ID_jTextField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(name_jTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(82, 82, 82))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ID_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(30, 30, 30)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(name_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(30, 30, 30)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(price_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(30, 30, 30)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(date_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(30, 30, 30)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(des_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(30, 30, 30)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(68, 68, 68))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(add_jButton)
                .addGap(33, 33, 33))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(206, Short.MAX_VALUE)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(206, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel6, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout add_tour_jDialogLayout = new javax.swing.GroupLayout(add_tour_jDialog.getContentPane());
        add_tour_jDialog.getContentPane().setLayout(add_tour_jDialogLayout);
        add_tour_jDialogLayout.setHorizontalGroup(
            add_tour_jDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        add_tour_jDialogLayout.setVerticalGroup(
            add_tour_jDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel8.setLayout(new java.awt.BorderLayout());

        jPanel9.setBackground(new java.awt.Color(207, 207, 207));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Cập Nhật Tour Du Lịch");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 1033, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel11)
                .addGap(30, 30, 30))
        );

        jPanel8.add(jPanel9, java.awt.BorderLayout.PAGE_START);

        jPanel10.setBackground(new java.awt.Color(190, 223, 232));

        jPanel11.setBackground(new java.awt.Color(255, 255, 204));

        jLabel12.setText("ID Tour cũ :");

        jLabel13.setText("Tên Tour :");

        jLabel14.setText("Giá Tour :");

        jLabel15.setText("Ngày Tạo :");

        jLabel16.setText("Điểm Đến :");

        jLabel17.setText("Ghi Chú :");

        ID_old_jTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ID_old_jTextFieldActionPerformed(evt);
            }
        });

        update_jButton1.setBackground(new java.awt.Color(255, 204, 204));
        update_jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        update_jButton1.setText("Cập Nhật");
        update_jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_jButton1ActionPerformed(evt);
            }
        });

        note_update_jTextArea.setColumns(20);
        note_update_jTextArea.setRows(5);
        jScrollPane3.setViewportView(note_update_jTextArea);

        jLabel19.setText("ID Tour mới :");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(94, 94, 94)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(update_jButton1)
                        .addComponent(des_update_jTextField)
                        .addComponent(date_update_jTextField)
                        .addComponent(price_update_jTextField)
                        .addComponent(ID_old_jTextField, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(name_update_jTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE)
                        .addComponent(ID_update_jTextField, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(82, 82, 82))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ID_old_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(30, 30, 30)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(ID_update_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(name_update_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(30, 30, 30)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(price_update_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGap(30, 30, 30)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(date_update_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addGap(30, 30, 30)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(des_update_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addGap(30, 30, 30)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addGap(68, 68, 68))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(update_jButton1)
                .addGap(33, 33, 33))
        );

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap(206, Short.MAX_VALUE)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(206, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel8.add(jPanel10, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout update_tour_jDialogLayout = new javax.swing.GroupLayout(update_tour_jDialog.getContentPane());
        update_tour_jDialog.getContentPane().setLayout(update_tour_jDialogLayout);
        update_tour_jDialogLayout.setHorizontalGroup(
            update_tour_jDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        update_tour_jDialogLayout.setVerticalGroup(
            update_tour_jDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(221, 226, 228));

        jPanel3.setBackground(new java.awt.Color(207, 207, 207));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Danh Sách Tour Du Lịch");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(190, 223, 232));

        Tour_jTable.setBackground(new java.awt.Color(255, 255, 204));
        Tour_jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(Tour_jTable);

        sort_jComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ID", "Name", "Date", "Price", " " }));
        sort_jComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sort_jComboBoxActionPerformed(evt);
            }
        });

        jLabel2.setText("Sort by:");

        add_view_jButton.setBackground(new java.awt.Color(0, 153, 51));
        add_view_jButton.setForeground(new java.awt.Color(255, 255, 255));
        add_view_jButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qltour/images/add (1).png"))); // NOI18N
        add_view_jButton.setText("Thêm");
        add_view_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_view_jButtonActionPerformed(evt);
            }
        });

        update_view_jButton.setBackground(new java.awt.Color(255, 204, 204));
        update_view_jButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qltour/images/edit-v2 (2).png"))); // NOI18N
        update_view_jButton.setText("Sửa");
        update_view_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_view_jButtonActionPerformed(evt);
            }
        });

        del_jButton.setBackground(new java.awt.Color(153, 0, 51));
        del_jButton.setForeground(new java.awt.Color(255, 255, 255));
        del_jButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qltour/images/rubbish-bin (1).png"))); // NOI18N
        del_jButton.setText("Xóa");
        del_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                del_jButtonActionPerformed(evt);
            }
        });

        jLabel3.setText("Search");

        Search_jTextField.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                Search_jTextFieldCaretUpdate(evt);
            }
        });
        Search_jTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Search_jTextFieldActionPerformed(evt);
            }
        });
        Search_jTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Search_jTextFieldKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(Search_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sort_jComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 968, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(add_view_jButton, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(update_view_jButton, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(del_jButton, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                    .addComponent(sort_jComboBox, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3)
                    .addComponent(Search_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 469, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(del_jButton)
                    .addComponent(update_view_jButton)
                    .addComponent(add_view_jButton))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void sort_jComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sort_jComboBoxActionPerformed
        // TODO add your handling code here:
        String sortby = String.valueOf(sort_jComboBox.getSelectedItem());
        if (sortby.equals("ID")) {
            listTour.sort(new Comparator<Tour>() {
                @Override
                public int compare(Tour o1, Tour o2) {
                    return o1.getID_Tour().compareTo(o2.getID_Tour());
                }
            });

        } else if (sortby.equals("Name")) {
            listTour.sort(new Comparator<Tour>() {
                @Override
                public int compare(Tour o1, Tour o2) {
                    return o1.getName_Tour().compareTo(o2.getName_Tour());
                }
            });

        } else if (sortby.equals("Date")) {
            listTour.sort(new Comparator<Tour>() {
                @Override
                public int compare(Tour o1, Tour o2) {
                    return o1.getDate_create().compareTo(o2.getDate_create());
                }
            });
        } else {
            listTour.sort(new Comparator<Tour>() {
                @Override
                public int compare(Tour o1, Tour o2) {
                    return (int) (o1.getPrice_Tour() - o2.getPrice_Tour());
                }
            });
        }
        o.saveData(listTour, "dsTour1.dat");
        setTable();
    }//GEN-LAST:event_sort_jComboBoxActionPerformed

    private void update_view_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_view_jButtonActionPerformed
        // TODO add your handling code here:
        update_tour_jDialog.setSize(1000, 600);
        update_tour_jDialog.setVisible(true);

    }//GEN-LAST:event_update_view_jButtonActionPerformed

    private void add_view_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_view_jButtonActionPerformed
        // TODO add your handling code here:
        add_tour_jDialog.setSize(1000, 600);
        add_tour_jDialog.setVisible(true);
    }//GEN-LAST:event_add_view_jButtonActionPerformed

    private void add_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_jButtonActionPerformed
        // TODO add your handling code here:
        listTour = o.loadData(listTour, "dsTour1.dat");

        double price = 0;
        date_jTextField.setText(String.valueOf(LocalDate.now()));
        String date = date_jTextField.getText();
        String ID = ID_jTextField.getText();
        String name = name_jTextField.getText();
        boolean priceinput = false;
        while (!priceinput) {
            try {
                price = Double.parseDouble(price_jTextField.getText());

                priceinput = true;
            } catch (NumberFormatException e) {
                e.getMessage();
                Tour_jOptionPane.showMessageDialog(add_tour_jDialog, "Price must be number ", "Thông Báo", Tour_jOptionPane.ERROR_MESSAGE);
                break;
            }

        }
        String des = des_jTextField.getText();
        String note = note_jTextArea.getText();
        check_Loi n = new check_Loi();
        int checkID = n.erros_same_IDTour_v1(listTour, ID);
        if (ID.isEmpty()) {
            Tour_jOptionPane.showMessageDialog(add_tour_jDialog, "ID không được rỗng   ", "Thông Báo", Tour_jOptionPane.ERROR_MESSAGE);

        } else if (name.isEmpty()) {
            Tour_jOptionPane.showMessageDialog(add_tour_jDialog, "Name không được rỗng   ", "Thông Báo", Tour_jOptionPane.ERROR_MESSAGE);
        } else if (des.isEmpty()) {
            Tour_jOptionPane.showMessageDialog(add_tour_jDialog, "Địa điểm không được rỗng   ", "Thông Báo", Tour_jOptionPane.ERROR_MESSAGE);
        } else if (checkID == 1) {
            Tour_jOptionPane.showMessageDialog(add_tour_jDialog, "ID đã tồn tại   ", "Thông Báo", Tour_jOptionPane.ERROR_MESSAGE);
        } else {
            Tour ntour = new Tour(ID, name, note, price, date, des);
            listTour.add(ntour);
            Tour_jOptionPane.showMessageDialog(add_tour_jDialog, "Thêm thành công ", "Thông Báo", Tour_jOptionPane.INFORMATION_MESSAGE);

        }
        o.saveData(listTour, "dsTour1.dat");

        setTable();
    }//GEN-LAST:event_add_jButtonActionPerformed

    private void update_jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_jButton1ActionPerformed
        // TODO add your handling code here:
        double pricenew = 0;
        int count = 0;
        String idOld = ID_old_jTextField.getText();
        String idnew = ID_update_jTextField.getText();
        String namenew = name_update_jTextField.getText();
        boolean priceinput = false;
        while (!priceinput) {
            try {
                pricenew = Double.parseDouble(price_update_jTextField.getText());

                priceinput = true;
            } catch (NumberFormatException e) {
                e.getMessage();
                Tour_jOptionPane.showMessageDialog(update_tour_jDialog, "Price must be number ", "Thông Báo", Tour_jOptionPane.ERROR_MESSAGE);

                break;

            }

        }

        String des = des_update_jTextField.getText();
        String note = note_update_jTextArea.getText();
        check_Loi n = new check_Loi();
//        Tour newtour = new Tour(idnew, namenew, note, pricenew, namenew, des);
        int checkID = n.erros_same_IDTour_v2(listTour, idnew, idOld);
        if (idOld.isEmpty()) {
            Tour_jOptionPane.showMessageDialog(update_tour_jDialog, "ID_old không được rỗng   ", "Thông Báo", Tour_jOptionPane.ERROR_MESSAGE);

        } else if (idnew.isEmpty()) {
            Tour_jOptionPane.showMessageDialog(update_tour_jDialog, "ID_new không được rỗng   ", "Thông Báo", Tour_jOptionPane.ERROR_MESSAGE);
        } else if (namenew.isEmpty()) {
            Tour_jOptionPane.showMessageDialog(update_tour_jDialog, "Name không được rỗng   ", "Thông Báo", Tour_jOptionPane.ERROR_MESSAGE);
        } else if (des.isEmpty()) {
            Tour_jOptionPane.showMessageDialog(update_tour_jDialog, "Địa điểm không được rỗng   ", "Thông Báo", Tour_jOptionPane.ERROR_MESSAGE);
        } else if (checkID == 1) {
            Tour_jOptionPane.showMessageDialog(update_tour_jDialog, "ID đã tồn tại ", "Thông Báo", Tour_jOptionPane.ERROR_MESSAGE);
        } else {
            for (Tour tour : listTour) {
                if (tour.getID_Tour().trim().toLowerCase().equals(idOld.trim().toLowerCase())) {
                    count++;
                    tour.setID_Tour(idnew);
                    tour.setName_Tour(namenew);
                    tour.setDestination(des);
                    tour.setNote(note);
                    tour.setPrice_Tour(pricenew);

                }

            }
            if (count == 0) {
                Tour_jOptionPane.showMessageDialog(update_tour_jDialog, "ID_old không tồn tại ", "Thông Báo", Tour_jOptionPane.ERROR_MESSAGE);
            } else {
                Tour_jOptionPane.showMessageDialog(update_tour_jDialog, "Cập nhật thành công ", "Thông Báo", Tour_jOptionPane.INFORMATION_MESSAGE);
            }
            o.saveData(listTour, "dsTour1.dat");
            setTable();
        }

    }//GEN-LAST:event_update_jButton1ActionPerformed

    private void ID_old_jTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ID_old_jTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ID_old_jTextFieldActionPerformed

    private void del_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_del_jButtonActionPerformed
        // TODO add your handling code here:
        int removeIndex = Tour_jTable.getSelectedRow();
        if (removeIndex == -1) {
            Tour_jOptionPane.showMessageDialog(update_tour_jDialog, "Vui lòng chọn dòng để xóa ", "Thông Báo", Tour_jOptionPane.ERROR_MESSAGE);
        } else if (listTour.size() == 0) {
            Tour_jOptionPane.showMessageDialog(update_tour_jDialog, "Bảng không có dữ liệu ", "Thông Báo", Tour_jOptionPane.ERROR_MESSAGE);
        } else {
            listTour.remove(removeIndex);
            Tour_jOptionPane.showMessageDialog(update_tour_jDialog, "Xóa thành công ", "Thông Báo", Tour_jOptionPane.ERROR_MESSAGE);

        }
        o.saveData(listTour, "dsTour1.dat");
        setTable();


    }//GEN-LAST:event_del_jButtonActionPerformed

    private void Search_jTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Search_jTextFieldActionPerformed
        // TODO add your handling code here:
        

    }//GEN-LAST:event_Search_jTextFieldActionPerformed

    private void Search_jTextFieldCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_Search_jTextFieldCaretUpdate
        // TODO add your handling code here:
    }//GEN-LAST:event_Search_jTextFieldCaretUpdate

    private void Search_jTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Search_jTextFieldKeyReleased
        // TODO add your handling code here:
        ArrayList<Tour> searchTour = new ArrayList<>();
        String search_field = Search_jTextField.getText();
        if (search_field.isEmpty()) {
            setTable();
        } else {
            for (Tour tour : listTour) {
                if (tour.getID_Tour().trim().toLowerCase().contains(search_field.trim().toLowerCase()) || tour.getName_Tour().trim().toLowerCase().contains(search_field.trim().toLowerCase()) || tour.getDestination().trim().toLowerCase().contains(search_field.trim().toLowerCase()) || String.valueOf(tour.getPrice_Tour()).trim().contains(search_field.trim())) {
                    searchTour.add(tour);
                }
            }
            DefaultTableModel defaultTableModel = new DefaultTableModel();
        Tour_jTable.setModel(defaultTableModel);
        ListSelectionModel listSelectionModel = Tour_jTable.getSelectionModel();
        listSelectionModel.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        defaultTableModel.addColumn("STT");
        defaultTableModel.addColumn("ID");
        defaultTableModel.addColumn("Tên Tour");
        defaultTableModel.addColumn("Ngày Tạo");
        defaultTableModel.addColumn("Điểm Đến");
        defaultTableModel.addColumn("Giá");
        defaultTableModel.addColumn("Ghi Chú");
        
        int i = 0;
        for (Tour tour : searchTour) {
            i++;
            defaultTableModel.addRow(new Object[]{i, tour.getID_Tour(), tour.getName_Tour(), tour.getDate_create(), tour.getDestination(), tour.getPrice_Tour(), tour.getNote()});
        }
        }
    }//GEN-LAST:event_Search_jTextFieldKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ID_jTextField;
    private javax.swing.JTextField ID_old_jTextField;
    private javax.swing.JTextField ID_update_jTextField;
    private javax.swing.JTextField Search_jTextField;
    private javax.swing.JOptionPane Tour_jOptionPane;
    private javax.swing.JTable Tour_jTable;
    private javax.swing.JButton add_jButton;
    private javax.swing.JDialog add_tour_jDialog;
    private javax.swing.JButton add_view_jButton;
    private javax.swing.JTextField date_jTextField;
    private javax.swing.JTextField date_update_jTextField;
    private javax.swing.JButton del_jButton;
    private javax.swing.JTextField des_jTextField;
    private javax.swing.JTextField des_update_jTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField name_jTextField;
    private javax.swing.JTextField name_update_jTextField;
    private javax.swing.JTextArea note_jTextArea;
    private javax.swing.JTextArea note_update_jTextArea;
    private javax.swing.JTextField price_jTextField;
    private javax.swing.JTextField price_update_jTextField;
    private javax.swing.JComboBox<String> sort_jComboBox;
    private javax.swing.JButton update_jButton1;
    private javax.swing.JDialog update_tour_jDialog;
    private javax.swing.JButton update_view_jButton;
    // End of variables declaration//GEN-END:variables
}
